import Image from "next/image"
import Link from "next/link"
import { ArrowUpRight } from "lucide-react"
import { Footer } from "@/components/footer"
import { Navbar } from "@/components/navbar"
import { leadership, mission, organization, programAreas, tagline } from "@/lib/data"
import { pageMetadata } from "@/lib/page-metadata"

export const metadata = pageMetadata(
  "About",
  "Learn about Seeds of Life Global Inc., a non-stock, non-profit organization in Sibonga, Cebu.",
  "/about",
)

export default function AboutPage() {
  return <><Navbar /><main id="main-content" className="overflow-hidden bg-[#f7f3e9] pt-[4.75rem]">
    <section className="relative isolate overflow-hidden bg-[#173b2a] px-4 py-20 text-white sm:px-6 sm:py-28 lg:px-8 lg:py-36"><Image src="/photos/children-day-gathering.webp" alt="Children and adults gathered beneath a covered court" fill priority sizes="100vw" className="-z-20 object-cover object-[center_62%]" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(10,31,21,.94)_0%,rgba(10,31,21,.72)_50%,rgba(10,31,21,.35)_100%)]" /><div className="mx-auto max-w-[88rem]"><p className="eyebrow text-[#e8c957]">Who we are</p><h1 className="display-type mt-6 max-w-5xl text-5xl font-bold leading-[.92] sm:text-7xl lg:text-[clamp(5rem,9vw,8.5rem)]">Grounded in faith.<br />Rooted in community.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-white/85">{tagline}</p></div></section>

    <section className="border-b border-[#173b2a]/15 bg-[#f0eadc] px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto grid max-w-[88rem] gap-10 lg:grid-cols-[.42fr_1fr] lg:gap-20"><p className="eyebrow text-[#a75434]">Our mission</p><div><h2 className="display-type max-w-4xl text-4xl font-bold leading-[1] text-[#173b2a] sm:text-6xl">Nurturing purpose in every child.</h2><p className="mt-8 max-w-3xl text-lg leading-8 text-[#526659]">{mission}</p></div></div></section>

    <section className="mx-auto grid max-w-[88rem] gap-12 px-4 py-20 sm:px-6 sm:py-28 lg:grid-cols-[.42fr_1fr] lg:gap-20 lg:px-8 lg:py-36"><p className="eyebrow text-[#a75434]">Why we exist</p><div><h2 className="display-type max-w-4xl text-4xl font-bold leading-[1.02] text-[#173b2a] sm:text-6xl">To make room for learning, care, and shared growth.</h2><p className="mt-8 max-w-2xl text-lg leading-8 text-[#526659]">We are Seeds of Life Global, a Philippine non-stock, non-profit organization based in Sibonga, Cebu. We help children discover purpose and grow in faith, character, and confidence.</p><p className="mt-5 max-w-2xl leading-8 text-[#526659]">Our wider vision includes opportunities for young people to learn, families to build practical skills, and communities to care for each other and their environment.</p></div></section>

    <section className="bg-[#e9e1d0]"><div className="mx-auto grid max-w-[88rem] lg:grid-cols-[1.05fr_.95fr]"><div className="relative min-h-[26rem] sm:min-h-[34rem]"><Image src="/photos/community-gathering.webp" alt="Children and adults gathered for a group photo outdoors" fill sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover object-[center_58%]" /></div><div className="flex flex-col justify-center px-4 py-16 sm:px-6 sm:py-20 lg:px-16 xl:px-24"><p className="eyebrow text-[#a75434]">Where we serve</p><h2 className="display-type mt-6 text-4xl font-bold leading-[1] text-[#173b2a] sm:text-5xl">Rooted in Sibonga, Cebu.</h2><p className="mt-7 max-w-md leading-8 text-[#526659]">Our home is {organization.location}. Here, our Bible study classes bring children, youth, and parents together. Our work with leaders and partners also connects us with communities across the Philippines and Asia.</p><Link href="/contact" className="editorial-link mt-9 text-[#173b2a]">Contact Seeds of Life <ArrowUpRight aria-hidden="true" className="h-4 w-4" /></Link></div></div></section>

    <section className="relative isolate bg-[#2d5139] px-4 py-20 text-white sm:px-6 sm:py-28 lg:px-8"><div className="absolute inset-0 -z-10 opacity-20 [background-image:radial-gradient(#e8c957_1px,transparent_1px)] [background-size:18px_18px]" /><div className="mx-auto grid max-w-[88rem] gap-12 lg:grid-cols-[.42fr_1fr] lg:gap-20"><p className="eyebrow text-[#e8c957]">Rooted in faith</p><div><blockquote className="display-type max-w-4xl text-5xl font-bold leading-[.95] sm:text-7xl">&quot;I am the vine; you are the branches...&quot;</blockquote><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-[#e8c957]">John 15:5</p><p className="mt-8 max-w-2xl leading-8 text-white/75">We believe lasting growth comes from abiding in Christ. This conviction guides our care for children and our commitment to helping them discover their gifts and serve others.</p></div></div></section>

    <section className="mx-auto max-w-[88rem] px-4 py-20 sm:px-6 sm:py-28 lg:px-8 lg:py-36"><div className="grid gap-10 lg:grid-cols-[.42fr_1fr] lg:gap-20"><p className="eyebrow text-[#a75434]">Our purpose</p><div><h2 className="display-type max-w-3xl text-4xl font-bold leading-[1] text-[#173b2a] sm:text-6xl">Five areas that guide our wider vision.</h2><div className="mt-12 divide-y divide-[#173b2a]/15 border-y border-[#173b2a]/15">{programAreas.map((area) => <article key={area.title} className="grid gap-4 py-6 sm:grid-cols-[4rem_1fr]"><span className="display-type text-3xl text-[#a75434]">{area.number}</span><div><h3 className="text-xl font-bold uppercase tracking-[.04em] text-[#173b2a]">{area.title}</h3><p className="mt-2 max-w-2xl leading-7 text-[#526659]">{area.summary}</p></div></article>)}</div></div></div></section>

    <section className="border-y border-[#173b2a]/15 bg-[#f0eadc] px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto grid max-w-[88rem] gap-10 lg:grid-cols-[.42fr_1fr] lg:gap-20"><p className="eyebrow text-[#a75434]">Leadership</p><div><h2 className="display-type max-w-4xl text-4xl font-bold leading-[1] text-[#173b2a] sm:text-6xl">Leading with purpose, faith, and care.</h2><div className="mt-12 grid gap-6 lg:grid-cols-2">{leadership.map((leader) => <article key={leader.name} className="overflow-hidden border border-[#173b2a]/15 bg-[#f7f3e9]"><div className="relative aspect-[4/5] bg-[#dce5cf]"><Image src={leader.image} alt={`${leader.name}, ${leader.role}`} fill sizes="(max-width: 1024px) 100vw, 42vw" className={`object-cover ${leader.imagePosition}`} /></div><div className="p-7 sm:p-9"><p className="eyebrow text-[#a75434]">{leader.role}</p><h3 className="display-type mt-5 text-3xl font-bold leading-none text-[#173b2a] sm:text-4xl">{leader.name}</h3><p className="mt-6 leading-7 text-[#526659]">{leader.summary}</p><Link href={`/leadership/${leader.slug}`} className="editorial-link mt-8 text-[#173b2a]">Read full profile <ArrowUpRight aria-hidden="true" className="h-4 w-4" /></Link></div></article>)}</div></div></div></section>

    <section className="border-y border-[#173b2a]/15 bg-[#dce5cf] px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-[88rem]"><p className="eyebrow text-[#a75434]">Organizational information</p><dl className="mt-8 grid gap-8 md:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs font-bold uppercase tracking-[.15em] text-[#526659]">Organization</dt><dd className="mt-3 text-lg font-bold text-[#173b2a]">{organization.name}</dd></div><div><dt className="text-xs font-bold uppercase tracking-[.15em] text-[#526659]">Status</dt><dd className="mt-3 text-lg font-bold text-[#173b2a]">Non-stock / non-profit</dd></div><div><dt className="text-xs font-bold uppercase tracking-[.15em] text-[#526659]">Classification</dt><dd className="mt-3 text-lg font-bold text-[#173b2a]">{organization.classification}</dd></div><div><dt className="text-xs font-bold uppercase tracking-[.15em] text-[#526659]">Corporate existence</dt><dd className="mt-3 text-lg font-bold text-[#173b2a]">Perpetual</dd></div></dl></div></section>
  </main><Footer /></>
}
