export const galleryPhotos = [
  { src: "/photos/community-study-circle.webp", alt: "Children and adults seated together in an outdoor learning circle", caption: "Learning together outdoors" },
  { src: "/photos/community-gathering.webp", alt: "Children and adults posing together outdoors near a basketball hoop", caption: "A community gathering" },
  { src: "/photos/children-celebration.webp", alt: "Children taking part in a lively group activity", caption: "Children celebrating" },
  { src: "/photos/small-group-study.webp", alt: "Children and adults seated in a small group outside a home", caption: "A small group learning together" },
  { src: "/photos/outdoor-volunteers.webp", alt: "Adults standing together outdoors beneath palm trees", caption: "Gathering outdoors" },
  { src: "/photos/leader-training.webp", alt: "Participants holding certificates after a group training session", caption: "A training gathering" },
  { src: "/photos/relief-volunteers.webp", alt: "Volunteers preparing supplies at an outdoor table", caption: "Preparing supplies together" },
  { src: "/photos/relief-distribution.webp", alt: "Community members sharing packed supplies outdoors", caption: "Sharing practical support" },
  { src: "/photos/children-day-tent.webp", alt: "Children together beneath a tent at a celebration", caption: "A children’s celebration" },
  { src: "/photos/community-auditorium.webp", alt: "Families and children gathered in a hall", caption: "A gathering indoors" },
  { src: "/photos/children-group-outdoors.webp", alt: "Children gathered outdoors with adults near a building", caption: "Children together outdoors" },
  { src: "/photos/community-learning-outdoors.webp", alt: "An adult speaking with children gathered outdoors", caption: "Learning as a group" },
  { src: "/photos/children-group-celebration.webp", alt: "Children and adults smiling together beneath a canopy", caption: "A shared celebration" },
  { src: "/photos/pavilion-gathering.webp", alt: "A group of children and adults posing beneath an outdoor pavilion", caption: "Together beneath the pavilion" },
  { src: "/photos/teaching-presentation.webp", alt: "Two women speaking beside a display of learning materials", caption: "Sharing a lesson" },
  { src: "/photos/children-reading.webp", alt: "Children and adults reading together in a small circle", caption: "Reading together" },
  { src: "/photos/team-gathering.webp", alt: "Adults and young people gathered together in a meeting room", caption: "A team gathering" },
  { src: "/photos/children-day-gathering.webp", alt: "A large group of children and adults celebrating beneath a covered court", caption: "A day together" },
  { src: "/photos/children-day-outdoors.webp", alt: "Children and adults gathered for a large outdoor group photo", caption: "A group celebration outdoors" },
  { src: "/photos/supplies-preparation.webp", alt: "Adults packing bags of supplies together", caption: "Preparing bags together" },
  { src: "/photos/relief-team.webp", alt: "A group of adults posing together after a community relief activity", caption: "A team sharing support" },
  { src: "/photos/supplies-carried.webp", alt: "A child carrying a packed bag among adults preparing supplies", caption: "Helping hands" },
  { src: "/photos/community-portrait.webp", alt: "A woman standing with children outside a home", caption: "A moment with children" },
  { src: "/photos/community-care.webp", alt: "A woman holding bags of vegetables in a community room", caption: "Sharing practical care" },
  { src: "/photos/mt-moriah/IMG_2145.jpg", alt: "People standing beside the Mt. Moriah Camp Site signs", caption: "At Mt. Moriah Camp Site" },
  { src: "/photos/mt-moriah/IMG_2104.jpg", alt: "A group standing beside the Mt. Moriah sign", caption: "Together at Mt. Moriah" },
  { src: "/photos/mt-moriah/IMG_4057.jpg", alt: "Children and adults gathered beneath a shelter at Mt. Moriah", caption: "A campsite gathering" },
  { src: "/photos/mt-moriah/IMG_4084.jpg", alt: "Young people sharing a meal at an outdoor table", caption: "Sharing a meal outdoors" },
  { src: "/photos/mt-moriah/IMG_3973.jpg", alt: "Children and adults taking part in an outdoor group activity", caption: "An outdoor group activity" },
  { src: "/Gallery/image1.jpg", alt: "Seeds of Life Global community gathering outdoors in Cebu", caption: "Community gathering" },
  { src: "/Gallery/image2.jpg", alt: "Children and adults together during an outdoor learning session", caption: "Learning together" },
  { src: "/Gallery/image3.jpg", alt: "Seeds of Life Global community members gathered with children outdoors in Cebu", caption: "Community celebration" },
] as const
