import Image from "next/image"
import Link from "next/link"
import { ArrowUpRight } from "lucide-react"
import { CommunityPhoto } from "@/components/community-photo"
import { Footer } from "@/components/footer"
import { Navbar } from "@/components/navbar"
import { currentImpact, currentInitiative, ministryFocuses, programAreas } from "@/lib/data"
import { pageMetadata } from "@/lib/page-metadata"

export const metadata = pageMetadata(
  "Programs",
  "Explore our approach to children’s development, our planned trainer practicum, and our wider vision for community care.",
  "/programs",
)

export default function ProgramsPage() {
  return <><Navbar /><main id="main-content" className="bg-[#f7f3e9] pt-[4.75rem] text-[#173b2a] [&_section]:scroll-mt-19">
    <section className="relative isolate min-h-[34rem] overflow-hidden bg-[#173b2a] px-4 py-16 text-white sm:px-6 sm:py-24 lg:min-h-[42rem] lg:px-8 lg:py-24"><Image src="/photos/small-group-study.webp" alt="Children and adults seated together in a small group outdoors" fill priority unoptimized sizes="100vw" className="-z-20 object-cover object-center" style={{ animation: "none" }} /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(12,39,27,.84),rgba(12,39,27,.55),rgba(12,39,27,.35))]" /><div className="relative mx-auto flex min-h-[23rem] max-w-[88rem] items-end"><div className="max-w-3xl"><p className="text-sm font-semibold text-[#e8c957]">Areas of purpose</p><h1 className="display-type mt-6 text-5xl font-bold leading-[.92] sm:text-7xl lg:text-[clamp(4rem,6vw,6rem)]">Growth looks<br />different for<br />every community.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-white/80">We bring children, families, and leaders together to grow in faith and purpose. Our wider vision includes learning, practical skills, community care, and partnership.</p><div className="mt-6 flex flex-wrap gap-x-7 gap-y-3"><a href="#current-work" className="inline-flex min-h-11 items-center border-b border-white text-sm font-semibold">Current activities</a><a href="#planned-initiative" className="inline-flex min-h-11 items-center border-b border-white text-sm font-semibold">Planned initiative</a><a href="#wider-vision" className="inline-flex min-h-11 items-center border-b border-white text-sm font-semibold">Wider vision</a></div></div></div></section>

    <section id="current-work" aria-labelledby="current-work-title" className="px-4 py-16 sm:px-6 sm:py-24 lg:px-8">
      <div className="mx-auto max-w-[88rem]">
        <div className="grid items-center gap-10 lg:grid-cols-[1fr_1.1fr] lg:gap-20">
          <div><p className="text-sm font-semibold text-[#526659]">Current work in Sibonga</p><h2 id="current-work-title" className="display-type mt-4 text-4xl font-bold leading-[1.06] sm:text-5xl">Learning and growing<br />together in faith.</h2><p className="mt-6 text-sm font-semibold text-[#345040]">{currentImpact.program.status}</p><h3 className="mt-3 text-xl font-bold">{currentImpact.program.title}</h3><p className="mt-5 max-w-xl text-lg leading-8 text-[#345040]">{currentImpact.program.description}</p><p className="mt-4 max-w-xl leading-8 text-[#345040]">Talk with us about class schedules and how your family or community can participate.</p><Link href="/contact" className="mt-6 inline-flex min-h-11 items-center border-b border-[#173b2a] text-sm font-semibold">Ask about classes</Link></div>
          <CommunityPhoto src="/photos/community-study-circle.webp" alt="Children seated outdoors while a teacher speaks with them" caption="Learning together in our community." />
        </div>
        <aside className="mt-12 grid gap-5 rounded-[.4rem] bg-[#e1e9d7] p-6 sm:p-9 lg:grid-cols-[.8fr_1.2fr] lg:gap-16"><div><p className="text-sm font-semibold text-[#526659]">{currentImpact.mtMoriah.status}</p><h3 className="display-type mt-3 text-3xl font-bold">{currentImpact.mtMoriah.title}</h3></div><div><p className="max-w-2xl leading-8 text-[#345040]">{currentImpact.mtMoriah.description}</p><Link href="/stories/mt-moriah-opening" className="mt-4 inline-flex min-h-11 items-center border-b border-[#173b2a] text-sm font-semibold">Read the Mt. Moriah story</Link></div></aside>
      </div>
    </section>

    <section className="bg-[#e8c957] px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><div className="mx-auto grid max-w-[88rem] gap-10 lg:grid-cols-[.42fr_1fr] lg:gap-20"><p className="text-sm font-semibold text-[#345040]">How we nurture</p><div><h2 className="display-type max-w-4xl text-4xl font-bold leading-[1] text-[#173b2a] sm:text-5xl">Faith, character, and care for others.</h2><p className="mt-7 max-w-2xl leading-8 text-[#345040]">Our approach to nurturing purpose brings together these four focus areas. Alongside them, our wider goals include practical skills, environmental care, and support for families in need.</p><div className="mt-10 grid gap-5 sm:grid-cols-2">{ministryFocuses.map((focus) => <article key={focus.title} className="border-t border-[#173b2a]/15 pt-5"><h3 className="text-lg font-semibold text-[#173b2a]">{focus.title}</h3><p className="mt-3 leading-7 text-[#345040]">{focus.description}</p></article>)}</div></div></div></section>

    <section id="planned-initiative" className="bg-[#173b2a] px-4 py-16 text-white sm:px-6 sm:py-24 lg:px-8"><div className="mx-auto grid max-w-[88rem] gap-10 lg:grid-cols-[.42fr_1fr] lg:gap-20"><p className="text-sm font-semibold text-[#e8c957]">Planned initiative</p><div><p className="text-sm font-semibold text-white/90">{currentInitiative.period} · Philippines</p><h2 className="display-type mt-5 max-w-4xl text-4xl font-bold leading-[1] sm:text-5xl">{currentInitiative.title}</h2><p className="mt-8 max-w-3xl text-lg leading-8 text-white/90">{currentInitiative.summary}</p><p className="mt-5 max-w-3xl border-l-4 border-[#e8c957] pl-4 text-sm leading-7 text-white/90">This remains a planned initiative. Please contact us to confirm its current status and dates before making arrangements.</p><p className="mt-5 max-w-3xl leading-8 text-white/90">Through supervised practice, we aim to help emerging trainers build their skills, grow in confidence, and develop a network of regional support.</p><p className="mt-6 max-w-2xl text-base font-semibold text-[#e8c957]">Equip one leader. Multiply the impact.</p><div className="mt-10 grid gap-8 border-t border-white/20 pt-7 md:grid-cols-2"><div><h3 className="text-sm font-semibold text-[#e8c957]">Training areas</h3><ul className="mt-4 grid gap-3 text-sm leading-6 text-white/90">{currentInitiative.skills.map((skill) => <li key={skill}>{skill}</li>)}</ul></div><div><h3 className="text-sm font-semibold text-[#e8c957]">Training resources</h3><ul className="mt-4 grid gap-3 text-sm leading-6 text-white/90">{currentInitiative.curriculum.map((resource) => <li key={resource}>{resource}</li>)}</ul><p className="mt-7 text-sm leading-6 text-white/90">We have planned six regional practicums for this project period. Get in touch with us for the latest scheduling and participation details.</p></div></div></div></div></section>

    <section id="wider-vision" aria-labelledby="wider-vision-title" className="bg-[#e1e9d7] px-4 py-16 sm:px-6 sm:py-24 lg:px-8">
      <div className="mx-auto grid max-w-[88rem] gap-10 lg:grid-cols-[.8fr_1.2fr] lg:gap-20">
        <div><p className="text-sm font-semibold text-[#526659]">Our wider goals</p><h2 id="wider-vision-title" className="display-type mt-4 text-4xl font-bold leading-[1.06] sm:text-5xl">Where we hope<br />to grow.</h2><p className="mt-6 max-w-md leading-8 text-[#345040]">These five areas guide our long-term vision. They are not a list of programs currently available; we welcome conversations about what could be built together.</p></div>
        <div className="divide-y divide-[#173b2a]/20 border-y border-[#173b2a]/20">{programAreas.map(area => <article key={area.title} className="py-7"><h3 className="display-type text-3xl font-bold leading-tight">{area.title}</h3><p className="mt-4 max-w-2xl leading-8 text-[#345040]">{area.summary}</p><ul className="mt-4 grid list-disc gap-2 pl-5 text-sm leading-6 text-[#345040]">{area.details.map(detail => <li key={detail}>{detail}</li>)}</ul></article>)}</div>
      </div>
    </section>

    <section className="mx-auto max-w-[88rem] px-4 py-16 sm:px-6 sm:py-24 lg:px-8">
      <div className="mb-9 grid gap-5 lg:grid-cols-[.34fr_.66fr] lg:gap-20"><p className="text-sm font-semibold text-[#526659]">Moments from our community</p><h2 className="display-type max-w-3xl text-4xl font-bold leading-[1] text-[#173b2a] sm:text-5xl">Learning and serving together.</h2></div>
      <div className="grid items-start gap-6 md:grid-cols-[1.1fr_.9fr_1fr]">
        <figure><div className="relative aspect-[4/3] overflow-hidden bg-[#dce5cf]"><Image src="/photos/children-group-outdoors.webp" alt="Children gathered outdoors with adults near a building" fill unoptimized sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><figcaption className="mt-3 text-sm text-[#526659]">Children together outdoors</figcaption></figure>
        <figure><div className="relative aspect-[4/3] overflow-hidden bg-[#dce5cf]"><Image src="/photos/community-learning-outdoors.webp" alt="An adult speaking with children gathered outdoors" fill unoptimized sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><figcaption className="mt-3 text-sm text-[#526659]">Learning as a group</figcaption></figure>
        <figure><div className="relative aspect-[4/3] overflow-hidden bg-[#dce5cf]"><Image src="/photos/relief-team.webp" alt="A group of adults posing after a community relief activity" fill unoptimized sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><figcaption className="mt-3 text-sm text-[#526659]">A team sharing support</figcaption></figure>
      </div><Link href="/gallery" className="mt-7 inline-flex min-h-11 items-center border-b border-[#173b2a] text-sm font-semibold">See more community photos</Link>
    </section>

    <section className="bg-[#e8c957] px-4 py-16 text-[#173b2a] sm:px-6 sm:py-24 lg:px-8"><div className="mx-auto grid max-w-[88rem] gap-8 lg:grid-cols-[.42fr_1fr] lg:gap-20"><p className="text-sm font-semibold text-[#173b2a]">A place to begin</p><div><h2 className="display-type max-w-3xl text-4xl font-bold leading-[1] sm:text-5xl">Ask what is possible today.</h2><p className="mt-6 max-w-xl leading-8 text-[#173b2a]/90">Tell us about your community, your interests, or the skills you would like to share. We can discuss current activities and possible ways to work together.</p><Link href="/contact" className="editorial-link mt-9 text-[#173b2a]">Talk with our team <ArrowUpRight aria-hidden="true" className="h-4 w-4" /></Link></div></div></section>
  </main><Footer /></>
}
