import Image from "next/image"
import Link from "next/link"
import { ArrowUpRight } from "lucide-react"
import { Footer } from "@/components/footer"
import { Navbar } from "@/components/navbar"
import { currentImpact, currentInitiative, ministryFocuses, programAreas } from "@/lib/data"
import { pageMetadata } from "@/lib/page-metadata"

export const metadata = pageMetadata(
  "Programs",
  "Explore our approach to children’s development, our planned trainer practicum, and our wider vision for community care.",
  "/programs",
)

export default function ProgramsPage() {
  return <><Navbar /><main id="main-content" className="overflow-hidden bg-[#f7f3e9] pt-[4.75rem]">
    <section className="relative isolate min-h-[34rem] overflow-hidden bg-[#173b2a] px-4 py-20 text-white sm:px-6 sm:py-28 lg:min-h-[42rem] lg:px-8 lg:py-36"><Image src="/photos/small-group-study.webp" alt="Children and adults seated together in a small group outdoors" fill priority sizes="100vw" className="-z-20 object-cover object-center" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(12,39,27,.94),rgba(12,39,27,.55),rgba(12,39,27,.35))]" /><div className="relative mx-auto flex min-h-[23rem] max-w-[88rem] items-end"><div className="max-w-3xl"><p className="eyebrow text-[#e8c957]">Areas of purpose</p><h1 className="display-type mt-6 text-5xl font-bold leading-[.92] sm:text-7xl lg:text-[clamp(5rem,9vw,8.5rem)]">Growth looks<br />different for<br />every community.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-white/80">We bring children, families, and leaders together to grow in faith and purpose. Our wider vision includes learning, practical skills, community care, and partnership.</p></div></div></section>

    <section className="mx-auto grid max-w-[88rem] gap-10 px-4 py-20 sm:px-6 sm:py-28 lg:grid-cols-[.42fr_1fr] lg:gap-20 lg:px-8 lg:py-36"><p className="eyebrow text-[#a75434]">Our work in Sibonga</p><div><h2 className="display-type max-w-4xl text-4xl font-bold leading-[1] text-[#173b2a] sm:text-6xl">Learning and growing together in faith.</h2><p className="mt-8 max-w-2xl text-lg leading-8 text-[#526659]">{currentImpact.program.description} Talk with us about class schedules and how your family or community can participate.</p></div></section>

    <section className="bg-[#e9e1d0] px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto grid max-w-[88rem] gap-10 lg:grid-cols-[.42fr_1fr] lg:gap-20"><p className="eyebrow text-[#a75434]">How we nurture</p><div><h2 className="display-type max-w-4xl text-4xl font-bold leading-[1] text-[#173b2a] sm:text-6xl">Faith, character, and care for others.</h2><p className="mt-7 max-w-2xl leading-8 text-[#526659]">Our approach to nurturing purpose brings together these four focus areas. Alongside them, our wider goals include practical skills, environmental care, and support for families in need.</p><div className="mt-10 grid gap-5 sm:grid-cols-2">{ministryFocuses.map((focus) => <article key={focus.title} className="border-t border-[#173b2a]/15 pt-5"><h3 className="text-xl font-bold uppercase tracking-[.04em] text-[#173b2a]">{focus.title}</h3><p className="mt-3 leading-7 text-[#526659]">{focus.description}</p></article>)}</div></div></div></section>

    <section className="bg-[#173b2a] px-4 py-20 text-white sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto grid max-w-[88rem] gap-10 lg:grid-cols-[.42fr_1fr] lg:gap-20"><p className="eyebrow text-[#e8c957]">Planned initiative</p><div><p className="eyebrow text-white/60">{currentInitiative.period} · Philippines</p><h2 className="display-type mt-5 max-w-4xl text-4xl font-bold leading-[1] sm:text-6xl">{currentInitiative.title}</h2><p className="mt-8 max-w-3xl text-lg leading-8 text-white/75">{currentInitiative.summary}</p><p className="mt-5 max-w-3xl leading-8 text-white/70">Through supervised practice, we aim to help emerging trainers build their skills, grow in confidence, and develop a network of regional support.</p><p className="mt-6 max-w-2xl text-sm font-bold uppercase tracking-[.14em] text-[#e8c957]">Equip one leader. Multiply the impact.</p><div className="mt-10 grid gap-8 border-t border-white/20 pt-7 md:grid-cols-2"><div><h3 className="eyebrow text-[#e8c957]">Training areas</h3><ul className="mt-4 grid gap-3 text-sm leading-6 text-white/75">{currentInitiative.skills.map((skill) => <li key={skill}>{skill}</li>)}</ul></div><div><h3 className="eyebrow text-[#e8c957]">Training resources</h3><ul className="mt-4 grid gap-3 text-sm leading-6 text-white/75">{currentInitiative.curriculum.map((resource) => <li key={resource}>{resource}</li>)}</ul><p className="mt-7 text-sm leading-6 text-white/65">We have planned six regional practicums for this project period. Get in touch with us for the latest scheduling and participation details.</p></div></div></div></div></section>

    <section className="border-y border-[#173b2a]/15"><div className="mx-auto max-w-[88rem]">{programAreas.map((area, index) => <article key={area.title} className={`grid gap-8 px-4 py-14 sm:px-6 sm:py-20 lg:grid-cols-[.34fr_.66fr] lg:gap-20 lg:px-8 lg:py-24 ${index % 2 === 1 ? "bg-[#ebe3d3]" : "bg-[#f7f3e9]"}`}><div className="flex items-start justify-between gap-6"><span className="display-type text-6xl leading-none text-[#a75434] sm:text-7xl">{area.number}</span><p className="eyebrow mt-2 text-right text-[#6b7d6b]">Our wider goals</p></div><div><h2 className="display-type max-w-3xl text-4xl font-bold leading-[.98] text-[#173b2a] sm:text-6xl">{area.title}</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-[#526659]">{area.summary}</p><div className="mt-9 flex flex-wrap gap-x-5 gap-y-3 border-t border-[#173b2a]/15 pt-5">{area.details.map((detail) => <span key={detail} className="text-xs font-bold uppercase tracking-[.13em] text-[#4f6954]">{detail}</span>)}</div></div></article>)}</div></section>

    <section className="mx-auto max-w-[88rem] px-4 py-20 sm:px-6 sm:py-28 lg:px-8">
      <div className="mb-9 grid gap-5 lg:grid-cols-[.34fr_.66fr] lg:gap-20"><p className="eyebrow text-[#a75434]">Moments from our community</p><h2 className="display-type max-w-3xl text-4xl font-bold leading-[1] text-[#173b2a] sm:text-5xl">Learning and serving together.</h2></div>
      <div className="grid gap-5 md:grid-cols-3">
        <figure><div className="relative aspect-[4/5] overflow-hidden bg-[#dce5cf]"><Image src="/photos/children-group-outdoors.webp" alt="Children gathered outdoors with adults near a building" fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><figcaption className="mt-3 text-sm text-[#526659]">Children together outdoors</figcaption></figure>
        <figure><div className="relative aspect-[4/5] overflow-hidden bg-[#dce5cf]"><Image src="/photos/community-learning-outdoors.webp" alt="An adult speaking with children gathered outdoors" fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><figcaption className="mt-3 text-sm text-[#526659]">Learning as a group</figcaption></figure>
        <figure><div className="relative aspect-[4/5] overflow-hidden bg-[#dce5cf]"><Image src="/photos/relief-team.webp" alt="A group of adults posing after a community relief activity" fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><figcaption className="mt-3 text-sm text-[#526659]">A team sharing support</figcaption></figure>
      </div>
    </section>

    <section className="bg-[#173b2a] px-4 py-20 text-white sm:px-6 sm:py-24 lg:px-8"><div className="mx-auto grid max-w-[88rem] gap-8 lg:grid-cols-[.42fr_1fr] lg:gap-20"><p className="eyebrow text-[#e8c957]">A place to begin</p><div><h2 className="display-type max-w-3xl text-4xl font-bold leading-[1] sm:text-6xl">Ask what is possible today.</h2><p className="mt-6 max-w-xl leading-8 text-white/70">Tell us about your community, your interests, or the skills you would like to share. We can discuss current activities and possible ways to work together.</p><Link href="/contact" className="editorial-link mt-9 text-[#e8c957]">Talk with our team <ArrowUpRight aria-hidden="true" className="h-4 w-4" /></Link></div></div></section>
  </main><Footer /></>
}
